// Hangmango French word bank v=001

const WORD_BANK_FR = {
  animaux: {
    easy:   ['CHAT', 'CHIEN', 'VACHE', 'POULE', 'LAPIN', 'CHEVAL', 'CANARD', 'MOUTON', 'COCHON', 'TIGRE', 'LION', 'LOUP', 'OURS', 'SINGE', 'DAUPHIN'],
    medium: ['GIRAFE', 'PINGOUIN', 'CHAMEAU', 'PERROQUET', 'TORTUE', 'RENARD', 'HIBOU', 'CASTOR', 'BALEINE', 'JAGUAR', 'POULPE', 'CROCODILE', 'SCORPION', 'FLAMANT', 'PANTHERE'],
    hard:   ['HIPPOPOTAME', 'RHINOCEROS', 'CHIMPANZE', 'ALBATROS', 'SALAMANDRE', 'ORNITHORYNQUE', 'TAMANOIR', 'FOURMILIER', 'KANGOUROU', 'MOUSTIQUE', 'SCARABEE', 'CORMORAN', 'MANDRILL', 'CAMELEON', 'PTERODACTYLE']
  },
  nourriture: {
    easy:   ['PAIN', 'LAIT', 'OEUF', 'RIZ', 'SOUPE', 'TARTE', 'SALADE', 'PIZZA', 'SUCRE', 'BEURRE', 'POMME', 'CITRON', 'MELON', 'CERISE', 'FRAISE'],
    medium: ['FROMAGE', 'POULET', 'SAUMON', 'CREVETTE', 'BROCOLI', 'POIVRON', 'FRAMBOISE', 'AUBERGINE', 'COURGETTE', 'CROISSANT', 'BRIOCHE', 'MOUTARDE', 'CANNELLE', 'NOISETTE', 'ABRICOT'],
    hard:   ['CHOUCROUTE', 'BOUILLABAISSE', 'RATATOUILLE', 'QUENELLE', 'BRANDADE', 'MADELEINE', 'PROFITEROLE', 'MERINGUE', 'MILLEFEUILLE', 'CARPACCIO', 'GOUGERE', 'FINANCIER', 'MACARON', 'BECHAMEL', 'HOLLANDAISE']
  },
  sports: {
    easy:   ['FOOT', 'TENNIS', 'GOLF', 'BOXE', 'RUGBY', 'VELO', 'NATATION', 'SKI', 'JUDO', 'YOGA', 'DANSE', 'COURSE', 'KAYAK', 'TIR', 'SURF'],
    medium: ['FOOTBALL', 'CYCLISME', 'ESCALADE', 'ESCRIME', 'PLONGEON', 'HANDBALL', 'BASEBALL', 'ATHLETISME', 'TRIATHLON', 'BADMINTON', 'PATINAGE', 'BOWLING', 'EQUITATION', 'AVIRON', 'VOILE'],
    hard:   ['PARACHUTISME', 'PENTATHLON', 'HALTEROPHILIE', 'MOTOCYCLISME', 'TRAMPOLINE', 'TAEKWONDO', 'DECATHLON', 'BIATHLON', 'BOBSLEIGH', 'ACROBATIE', 'DELTAPLANE', 'LANCEURDISQUE', 'ESCRIMEUR', 'WATERPOLO', 'PELOTANQUE']
  },
  pays: {
    easy:   ['FRANCE', 'ESPAGNE', 'ITALIE', 'CHINE', 'JAPON', 'BRESIL', 'CANADA', 'MAROC', 'INDE', 'EGYPTE', 'GRECE', 'SUISSE', 'MEXIQUE', 'RUSSIE', 'CUBA'],
    medium: ['ALLEMAGNE', 'PORTUGAL', 'AUSTRALIE', 'ARGENTINE', 'COLOMBIE', 'NIGERIA', 'VIETNAM', 'UKRAINE', 'PEROU', 'ALGERIE', 'ROUMANIE', 'HONGRIE', 'TUNISIE', 'PAKISTAN', 'SENEGAL'],
    hard:   ['MOZAMBIQUE', 'BANGLADESH', 'AZERBAIDJAN', 'MADAGASCAR', 'KAZAKHSTAN', 'GUATEMALA', 'CAMEROUN', 'ZIMBABWE', 'NICARAGUA', 'SALVADOR', 'TADJIKISTAN', 'OUZBEKISTAN', 'ETHIOPIE', 'MAURITANIE', 'BOTSWANA']
  },
  sciences: {
    easy:   ['ATOME', 'SOLEIL', 'LUNE', 'TERRE', 'EAU', 'FEU', 'VENT', 'PLUIE', 'NEIGE', 'RACINE', 'FLEUR', 'GRAINE', 'SANG', 'OS', 'PEAU'],
    medium: ['OXYGENE', 'CARBONE', 'GRAVITE', 'ECLIPSE', 'EROSION', 'PHOTON', 'NEURONE', 'BACTERIE', 'CELLULE', 'CIRCUIT', 'ISOTOPE', 'MOLECULE', 'HORMONE', 'ENZYME', 'COMETE'],
    hard:   ['PHOTOSYNTHESE', 'ECOSYSTEME', 'CHROMOSOME', 'METABOLISME', 'THERMODYNAMIQUE', 'ELECTROLYSE', 'RADIOACTIVITE', 'ASTROPHYSIQUE', 'MAGNETISME', 'CRISTALLOGRAPHIE', 'GEOMORPHOLOGIE', 'BIOCHIMIE', 'NEUROLOGIE', 'SPECTROSCOPIE', 'TECTONIQUE']
  },
  art: {
    easy:   ['PEINTURE', 'DESSIN', 'SCULPTURE', 'PHOTO', 'DANSE', 'THEATRE', 'CINEMA', 'MUSIQUE', 'ROMAN', 'POEME', 'FRESQUE', 'PORTRAIT', 'COULEUR', 'CRAYON', 'TOILE'],
    medium: ['AQUARELLE', 'GRAVURE', 'MOSAIQUE', 'CALLIGRAPHIE', 'CERAMIQUE', 'LITHOGRAPHIE', 'PASTEL', 'VITRAIL', 'TAPISSERIE', 'BRODERIE', 'COMEDIE', 'SYMPHONIE', 'CONCERTO', 'SONNET', 'FABLIAU'],
    hard:   ['IMPRESSIONNISME', 'SURREALISME', 'RENAISSANCE', 'BAROQUE', 'ROMANTISME', 'CUBISME', 'POINTILLISME', 'EXPRESSIONNISME', 'NATURALISME', 'SYMBOLISME', 'CLASSICISME', 'DADAISME', 'FUTURISME', 'REALISME', 'MODERNISME']
  },
  geographie: {
    easy:   ['MER', 'LAC', 'MONT', 'ILE', 'CAP', 'BAIE', 'GOLFE', 'DELTA', 'FORET', 'DESERT', 'PLAINE', 'COLLINE', 'FLEUVE', 'OCEAN', 'VALLEE'],
    medium: ['AMAZONE', 'SAHARA', 'HIMALAYA', 'ATLANTIQUE', 'PACIFIQUE', 'MEDITERRANEE', 'ARCTIQUE', 'FJORD', 'CASCADE', 'VOLCAN', 'PLATEAU', 'TOUNDRA', 'MANGROVE', 'SAVANE', 'TROPIQUE'],
    hard:   ['PATAGONIE', 'MESOPOTAMIE', 'PELOPONNESE', 'PYRENEES', 'KILIMANJARO', 'CARPATHES', 'CORDILLERE', 'MERIDIONAL', 'EQUATORIAL', 'SUBANTARCTIQUE', 'SUBARCTIQUE', 'TECTONIQUE', 'APPALACHIEN', 'CAUCASIEN', 'ANATOLIE']
  }
};

const CATEGORY_META_FR = {
  animaux:    { icon: '🐾', label: 'Animaux' },
  nourriture: { icon: '🍕', label: 'Nourriture' },
  sports:     { icon: '⚽', label: 'Sports' },
  pays:       { icon: '🌍', label: 'Pays' },
  sciences:   { icon: '🔬', label: 'Sciences' },
  art:        { icon: '🎨', label: 'Art' },
  geographie: { icon: '🗺️', label: 'Géographie' }
};

function getWordFR(category, difficulty) {
  const list = WORD_BANK_FR[category][difficulty];
  return list[Math.floor(Math.random() * list.length)];
}
