// Hangmango German word bank v=001

const WORD_BANK_DE = {
  tiere: {
    easy:   ['KATZE', 'HUND', 'KUH', 'HUHN', 'HASE', 'PFERD', 'ENTE', 'SCHAF', 'SCHWEIN', 'TIGER', 'LOEWE', 'WOLF', 'BAER', 'AFFE', 'DELFIN'],
    medium: ['GIRAFFE', 'PINGUIN', 'KAMEL', 'PAPAGEI', 'SCHILDKROETE', 'FUCHS', 'EULE', 'BIBER', 'WAL', 'JAGUAR', 'TINTENFISCH', 'KROKODIL', 'SKORPION', 'FLAMINGO', 'PANTHER'],
    hard:   ['NILPFERD', 'NASHORN', 'SCHIMPANSE', 'ALBATROS', 'SALAMANDER', 'SCHNABELTIER', 'AMEISENBÄR', 'KÄNGURU', 'MUECKE', 'KAEFER', 'KORMORAN', 'MANDRILL', 'CHAMÄLEON', 'FLEDERMAUS', 'OZELOT']
  },
  essen: {
    easy:   ['BROT', 'MILCH', 'EI', 'REIS', 'SUPPE', 'KUCHEN', 'SALAT', 'PIZZA', 'ZUCKER', 'BUTTER', 'APFEL', 'ZITRONE', 'MELONE', 'KIRSCHE', 'ERDBEERE'],
    medium: ['KÄSE', 'HUHN', 'LACHS', 'GARNELE', 'BROKKOLI', 'PAPRIKA', 'HIMBEERE', 'AUBERGINE', 'ZUCCHINI', 'BREZEL', 'BRATWURST', 'SENF', 'ZIMT', 'HASELNUSS', 'APRIKOSE'],
    hard:   ['SAUERBRATEN', 'SCHNITZEL', 'SPÄTZLE', 'LEBKUCHEN', 'STRUDEL', 'MARZIPAN', 'SAUERKRAUT', 'KARTOFFELSUPPE', 'RINDERBRATEN', 'SCHWARZWÄLDER', 'PUMPERNICKEL', 'CHRISTSTOLLEN', 'PFEFFERKUCHEN', 'ZWIEBELKUCHEN', 'GRÜNKOHL']
  },
  sport: {
    easy:   ['FUSSBALL', 'TENNIS', 'GOLF', 'BOXEN', 'RUGBY', 'RADFAHREN', 'SCHWIMMEN', 'SKIFAHREN', 'JUDO', 'YOGA', 'TANZEN', 'LAUFEN', 'KANU', 'SURFEN', 'SEGELN'],
    medium: ['VOLLEYBALL', 'BASKETBALL', 'KLETTERN', 'FECHTEN', 'TAUCHEN', 'HANDBALL', 'BASEBALL', 'LEICHTATHLETIK', 'TRIATHLON', 'BADMINTON', 'EISLAUFEN', 'BOWLING', 'REITEN', 'RUDERN', 'TURNEN'],
    hard:   ['FALLSCHIRMSPRINGEN', 'FUENFKAMPF', 'GEWICHTHEBEN', 'MOTORRADFAHREN', 'TRAMPOLINTURNEN', 'TAEKWONDO', 'ZEHNKAMPF', 'BIATHLON', 'BOBFAHREN', 'AKROBATIK', 'DRACHENFLIEGEN', 'WASSERBALL', 'BOGENSCHIESSEN', 'RADSPORT', 'STABHOCHSPRUNG']
  },
  laender: {
    easy:   ['DEUTSCHLAND', 'FRANKREICH', 'SPANIEN', 'ITALIEN', 'CHINA', 'JAPAN', 'BRASILIEN', 'KANADA', 'MAROKKO', 'INDIEN', 'AEGYPTEN', 'GRIECHENLAND', 'SCHWEIZ', 'MEXIKO', 'KUBA'],
    medium: ['PORTUGAL', 'AUSTRALIEN', 'ARGENTINIEN', 'KOLUMBIEN', 'NIGERIA', 'VIETNAM', 'UKRAINE', 'PERU', 'ALGERIEN', 'RUMAENIEN', 'UNGARN', 'TUNESIEN', 'PAKISTAN', 'SENEGAL', 'SCHWEDEN'],
    hard:   ['MOSAMBIK', 'BANGLADESCH', 'ASERBAIDSCHAN', 'MADAGASKAR', 'KASACHSTAN', 'GUATEMALA', 'KAMERUN', 'SIMBABWE', 'NICARAGUA', 'TADSCHIKISTAN', 'USBEKISTAN', 'AETHIOPIEN', 'MAURETANIEN', 'BOTSWANA', 'SLOWAKEI']
  },
  wissenschaft: {
    easy:   ['ATOM', 'SONNE', 'MOND', 'ERDE', 'WASSER', 'FEUER', 'WIND', 'REGEN', 'SCHNEE', 'WURZEL', 'BLUME', 'SAMEN', 'BLUT', 'KNOCHEN', 'HAUT'],
    medium: ['SAUERSTOFF', 'KOHLENSTOFF', 'SCHWERKRAFT', 'EKLIPSE', 'EROSION', 'PHOTON', 'NEURON', 'BAKTERIE', 'ZELLE', 'SCHALTKREIS', 'ISOTOP', 'MOLEKUEL', 'HORMON', 'ENZYM', 'KOMET'],
    hard:   ['PHOTOSYNTHESE', 'OEKOSYSTEM', 'CHROMOSOM', 'METABOLISMUS', 'THERMODYNAMIK', 'ELEKTROLYSE', 'GEOPHYSIK', 'ASTROPHYSIK', 'MAGNETISMUS', 'KRISTALLOGRAPHIE', 'GEOMORPHOLOGIE', 'BIOCHEMIE', 'NEUROLOGIE', 'SPEKTROSKOPIE', 'TEKTONIK']
  },
  geographie: {
    easy:   ['MEER', 'SEE', 'BERG', 'INSEL', 'KAP', 'BUCHT', 'GOLF', 'DELTA', 'WALD', 'WUESTE', 'EBENE', 'HUEGEL', 'FLUSS', 'OZEAN', 'TAL'],
    medium: ['AMAZONAS', 'SAHARA', 'HIMALAJA', 'ATLANTIK', 'PAZIFIK', 'MITTELMEER', 'ARKTIS', 'FJORD', 'WASSERFALL', 'VULKAN', 'HOCHEBENE', 'TUNDRA', 'MANGROVE', 'SAVANNE', 'TROPEN'],
    hard:   ['PATAGONIEN', 'MESOPOTAMIEN', 'PELOPONNES', 'PYRENÄEN', 'KILIMANDSCHARO', 'KARPATEN', 'KORDILLERE', 'MERIDIONAL', 'ÄQUATORIAL', 'SUBANTARKTIS', 'SUBARKTIS', 'TEKTONIK', 'APPALACHEN', 'KAUKASUS', 'ANATOLIEN']
  },
  musik: {
    easy:   ['BACH', 'BEETHOVEN', 'MOZART', 'BRAHMS', 'RHYTHMUS', 'MELODIE', 'KLAVIER', 'GEIGE', 'FLOETE', 'TROMMEL', 'HARFE', 'ORGEL', 'CHOR', 'NOTE', 'TAKT'],
    medium: ['SYMPHONIE', 'KONZERT', 'SONATE', 'TROMPETE', 'KLARINETTE', 'AKKORDEON', 'KONTRABASS', 'DIRIGENT', 'ORCHESTER', 'KAMMERMUSIK', 'VOLKSMUSIK', 'SCHLAGER', 'OPERETTE', 'LIEDERMACHER', 'BLASMUSIK'],
    hard:   ['POLYPHONIE', 'KONTRAPUNKT', 'KOMPOSITION', 'PHILHARMONIE', 'IMPROVISATION', 'DISSONANZ', 'MODULATION', 'SYNKOPE', 'ARPEGGIO', 'MUSIKTHEORIE', 'INSTRUMENTIERUNG', 'CHOROGRAPHIE', 'SINFONIETTA', 'KAMMERORCHESTER', 'GENERALBASS']
  },
  kunst: {
    easy:   ['MALEREI', 'ZEICHNUNG', 'SKULPTUR', 'FOTO', 'TANZ', 'THEATER', 'KINO', 'MUSIK', 'ROMAN', 'GEDICHT', 'FRESKO', 'PORTRAIT', 'FARBE', 'PINSEL', 'LEINWAND'],
    medium: ['AQUARELL', 'GRAVUR', 'MOSAIK', 'KALLIGRAPHIE', 'KERAMIK', 'LITHOGRAPHIE', 'PASTELL', 'GLASMALEREI', 'TAPISSERIE', 'STICKEREI', 'KOMOEDIE', 'SINFONIE', 'SONATE', 'SONETT', 'KUPFERSTICH'],
    hard:   ['IMPRESSIONISMUS', 'SURREALISMUS', 'RENAISSANCE', 'BAROCK', 'ROMANTISMUS', 'KUBISMUS', 'EXPRESSIONISMUS', 'NATURALISMUS', 'SYMBOLISMUS', 'KLASSIZISMUS', 'DADAISMUS', 'FUTURISMUS', 'REALISMUS', 'MODERNISMUS', 'BAUHAUS']
  }
};

const CATEGORY_META_DE = {
  tiere:        { icon: '🐾', label: 'Tiere' },
  essen:        { icon: '🍕', label: 'Essen' },
  sport:        { icon: '⚽', label: 'Sport' },
  laender:      { icon: '🌍', label: 'Länder' },
  wissenschaft: { icon: '🔬', label: 'Wissenschaft' },
  geographie:   { icon: '🗺️', label: 'Geographie' },
  musik:        { icon: '🎵', label: 'Musik' },
  kunst:        { icon: '🎨', label: 'Kunst' }
};

function getWordDE(category, difficulty) {
  const list = WORD_BANK_DE[category][difficulty];
  return list[Math.floor(Math.random() * list.length)];
}
