// Hangmango Brazilian Portuguese word bank v=001

const WORD_BANK_PT = {
  animais: {
    easy:   ['GATO', 'CACHORRO', 'VACA', 'GALINHA', 'COELHO', 'CAVALO', 'PATO', 'OVELHA', 'PORCO', 'TIGRE', 'LEAO', 'LOBO', 'URSO', 'MACACO', 'GOLFINHO'],
    medium: ['GIRAFA', 'PINGUIM', 'CAMELO', 'PAPAGAIO', 'TARTARUGA', 'RAPOSA', 'CORUJA', 'CASTOR', 'BALEIA', 'JAGUAR', 'POLVO', 'CROCODILO', 'ESCORPIAO', 'FLAMINGO', 'PANTERA'],
    hard:   ['HIPOPOTAMO', 'RINOCERONTE', 'CHIMPANZE', 'ALBATROS', 'SALAMANDRA', 'ORNITORRINCO', 'TAMANDUÁ', 'CANGURU', 'MOSQUITO', 'BESOURO', 'CORMORAO', 'MANDRIL', 'CAMALEAO', 'PTERODATILO', 'ANACONDA']
  },
  comida: {
    easy:   ['ARROZ', 'FEIJAO', 'PAO', 'LEITE', 'OVO', 'SOPA', 'TORTA', 'SALADA', 'PIZZA', 'ACUCAR', 'MANTEIGA', 'MACA', 'LIMAO', 'MELAO', 'CEREJA'],
    medium: ['FRANGO', 'SALMAO', 'CAMARAO', 'BROCOLIS', 'PIMENTAO', 'FRAMBOESA', 'BERINJELA', 'ABOBRINHA', 'CROISSANT', 'MOSTARDA', 'CANELA', 'AMENDOIM', 'ABACAXI', 'GOIABA', 'CAJU'],
    hard:   ['FEIJOADA', 'BRIGADEIRO', 'COXINHA', 'PASTELARIA', 'PÃODEQUEIJO', 'MOQUECA', 'ACARAJE', 'TUCUPI', 'VATAPA', 'CARURU', 'CALDEIRADA', 'ESCONDIDINHO', 'BOBODECARANGEJO', 'XINXIM', 'QUIBEBE']
  },
  esportes: {
    easy:   ['FUTEBOL', 'TENIS', 'GOLFE', 'BOXE', 'RUGBY', 'CICLISMO', 'NATACAO', 'ESQUI', 'JUDO', 'YOGA', 'DANCA', 'CORRIDA', 'CAIAQUE', 'SURFE', 'VELA'],
    medium: ['VOLEIBOL', 'BASQUETE', 'ESCALADA', 'ESGRIMA', 'MERGULHO', 'HANDEBOL', 'BEISEBOL', 'ATLETISMO', 'TRIATLO', 'BADMINTON', 'PATINACAO', 'BOLICHE', 'EQUITACAO', 'REMO', 'GINASTICA'],
    hard:   ['PARAQUEDISMO', 'PENTATLO', 'HALTEROFILISMO', 'MOTOCICLISMO', 'TRAMPOLIM', 'TAEKWONDO', 'DECATLO', 'BIATLO', 'BOBSLED', 'ACROBACIA', 'DELTAPLANE', 'ESGRIMA', 'WATERPOLO', 'PETECA', 'CAPOEIRA']
  },
  paises: {
    easy:   ['BRASIL', 'FRANCA', 'ESPANHA', 'ITALIA', 'CHINA', 'JAPAO', 'CANADA', 'MARROCOS', 'INDIA', 'EGITO', 'GRECIA', 'SUICA', 'MEXICO', 'RUSSIA', 'CUBA'],
    medium: ['ALEMANHA', 'PORTUGAL', 'AUSTRALIA', 'ARGENTINA', 'COLOMBIA', 'NIGERIA', 'VIETNAM', 'UCRANIA', 'PERU', 'ARGELIA', 'ROMENIA', 'HUNGRIA', 'TUNISIA', 'PAQUISTAO', 'SENEGAL'],
    hard:   ['MOCAMBIQUE', 'BANGLADESH', 'AZERBAIJAO', 'MADAGASCAR', 'CAZAQUISTAO', 'GUATEMALA', 'CAMAROES', 'ZIMBABUE', 'NICARAGUA', 'SALVADOR', 'TADJIQUISTAO', 'UZBEQUISTAO', 'ETIOPIA', 'MAURITANIA', 'BOTSWANA']
  },
  ciencias: {
    easy:   ['ATOMO', 'SOL', 'LUA', 'TERRA', 'AGUA', 'FOGO', 'VENTO', 'CHUVA', 'NEVE', 'RAIZ', 'FLOR', 'SEMENTE', 'SANGUE', 'OSSO', 'PELE'],
    medium: ['OXIGENIO', 'CARBONO', 'GRAVIDADE', 'ECLIPSE', 'EROSAO', 'FOTON', 'NEURONIO', 'BACTERIA', 'CELULA', 'CIRCUITO', 'ISOTOPO', 'MOLECULA', 'HORMONIO', 'ENZIMA', 'COMETA'],
    hard:   ['FOTOSSINTESE', 'ECOSSISTEMA', 'CROMOSSOMO', 'METABOLISMO', 'TERMODINAMICA', 'ELETROLISE', 'RADIOATIVIDADE', 'ASTROFISICA', 'MAGNETISMO', 'CRISTALOGRAFIA', 'GEOMORFOLOGIA', 'BIOQUIMICA', 'NEUROLOGIA', 'ESPECTROSCOPIA', 'TECTONICA']
  },
  geografia: {
    easy:   ['MAR', 'LAGO', 'MONTE', 'ILHA', 'CABO', 'BAIA', 'GOLFO', 'DELTA', 'FLORESTA', 'DESERTO', 'PLANICIE', 'COLINA', 'RIO', 'OCEANO', 'VALE'],
    medium: ['AMAZONIA', 'SAHARA', 'HIMALAIA', 'ATLANTICO', 'PACIFICO', 'MEDITERRANEO', 'ARTICO', 'FIORDE', 'CASCATA', 'VULCAO', 'PLANALTO', 'TUNDRA', 'MANGUEZAL', 'SAVANA', 'TROPICO'],
    hard:   ['PATAGONIA', 'MESOPOTAMIA', 'PELOPONESO', 'PIRENEUS', 'KILIMANJARO', 'CARPATOS', 'CORDILHEIRA', 'MERIDIONAL', 'EQUATORIAL', 'SUBANTARTICO', 'SUBARTICO', 'TECTONICA', 'APALACHES', 'CAUCASIANO', 'ANATOLIA']
  },
  musica: {
    easy:   ['SAMBA', 'FUNK', 'FORRO', 'JAZZ', 'ROCK', 'POP', 'BLUES', 'PIANO', 'VIOLAO', 'FLAUTA', 'BATERIA', 'VIOLINO', 'HARPA', 'RITMO', 'MELODIA'],
    medium: ['BOSSANOVA', 'PAGODE', 'AXE', 'REGGAE', 'CLASSICO', 'TROMPETE', 'ACORDEAO', 'TECLADO', 'CHORINHO', 'MARACATU', 'FREVO', 'BAIAO', 'TROPICALIA', 'MPB', 'REPENTE'],
    hard:   ['POLIFONIA', 'CONTRABAIXO', 'XILOFONE', 'FILARMONICA', 'CONTRALTO', 'IMPROVISACAO', 'CONTRAPONTO', 'SINCOPE', 'ARPEJO', 'SOLFEJO', 'PENTATONICO', 'GRAVACAO', 'ACUSTICA', 'COREOGRAFIA', 'ORQUESTRACAO']
  },
  natureza: {
    easy:   ['ARVORE', 'RIO', 'FLOR', 'PEDRA', 'NUVEM', 'CHUVA', 'VENTO', 'FOLHA', 'RAIZ', 'FRUTO', 'LAGO', 'PRAIA', 'MATO', 'TERRA', 'AREIA'],
    medium: ['FLORESTA', 'CACHOEIRA', 'PANTANAL', 'CERRADO', 'CAATINGA', 'MANGUE', 'RECIFE', 'CAVERNA', 'VULCAO', 'GELEIRA', 'SAVANA', 'RESTINGA', 'BREJO', 'DUNAS', 'CHAPADA'],
    hard:   ['BIODIVERSIDADE', 'ECOSSISTEMA', 'DESMATAMENTO', 'SUSTENTABILIDADE', 'REFLORESTAMENTO', 'AQUIFERO', 'TERMITEIRO', 'MICROCLIMA', 'BIOMA', 'PALEONTOLOGIA', 'ESTRATIFICACAO', 'FOTOTROPISMO', 'POLINIZACAO', 'HIBERNACAO', 'MIMETISMO']
  },
  cultura: {
    easy:   ['CARNAVAL', 'SAMBA', 'FESTA', 'DANCA', 'MUSICA', 'TEATRO', 'CINEMA', 'ARTE', 'LIVRO', 'POEMA', 'PINTURA', 'ESCULTURA', 'MUSEU', 'FOLCLORE', 'TRADICAO'],
    medium: ['CAPOEIRA', 'LITERATURA', 'ARQUITETURA', 'GASTRONOMIA', 'ARTESANATO', 'MAMULENGO', 'MARACATU', 'FREVO', 'QUILOMBO', 'BANDEIRANTE', 'BARROCO', 'MODERNISMO', 'TROPICALIA', 'CORDEL', 'CAIPIRA'],
    hard:   ['SINCRETISMO', 'BRASILIDADE', 'CARIOCA', 'INDIGENISMO', 'COLONIZACAO', 'INDEPENDENCIA', 'REPUBLICA', 'PATRIMONIO', 'IMATERIALIDADE', 'REGIONALISMO', 'MODERNIDADE', 'IDENTIDADE', 'DIVERSIDADE', 'MANIFESTACAO', 'TROPICALISMO']
  },
  historia: {
    easy:   ['REI', 'GUERRA', 'PAZ', 'POVO', 'TERRA', 'NACAO', 'REINO', 'IMPERIO', 'CIDADE', 'CASTELO', 'ESPADA', 'BANDEIRA', 'MAPA', 'HEROI', 'LENDA'],
    medium: ['DESCOBERTA', 'COLONIZACAO', 'NAVEGACAO', 'REVOLUCAO', 'REPUBLICA', 'INDEPENDENCIA', 'EXPLORACAO', 'DEMOCRACIA', 'CONSTITUICAO', 'BANDEIRANTE', 'EXPEDICAO', 'JESUITA', 'MONARQUIA', 'FEDERACAO', 'PROCLAMACAO'],
    hard:   ['INCONFIDENCIA', 'POSITIVISMO', 'ILUMINISMO', 'INDUSTRIALIZACAO', 'URBANIZACAO', 'BANDEIRISMO', 'REPUBLICANISMO', 'DESENVOLVIMENTISMO', 'PARLAMENTARISMO', 'FEDERALISMO', 'REDEMOCRATIZACAO', 'CONSTITUCIONALISMO', 'CONSTITUINTE', 'MODERNIZACAO', 'CENTRALIZACAO']
  }
};

const CATEGORY_META_PT = {
  animais:   { icon: '🐾', label: 'Animais' },
  comida:    { icon: '🍕', label: 'Comida' },
  esportes:  { icon: '⚽', label: 'Esportes' },
  paises:    { icon: '🌍', label: 'Países' },
  ciencias:  { icon: '🔬', label: 'Ciências' },
  geografia: { icon: '🗺️', label: 'Geografia' },
  musica:    { icon: '🎵', label: 'Música' },
  natureza:  { icon: '🌿', label: 'Natureza' },
  cultura:   { icon: '🎭', label: 'Cultura' },
  historia:  { icon: '📜', label: 'História' }
};

function getWordPT(category, difficulty) {
  const list = WORD_BANK_PT[category][difficulty];
  return list[Math.floor(Math.random() * list.length)];
}
